default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST", "mysql") %>
  port: <%= ENV.fetch("MYSQL_PORT", "3306") %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "root") %>
  ssl_mode: disabled

development:
  <<: *default
  database: jumbotron_dummy_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE", "jumbotron_dummy_test") %>
