version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  cst: cst/framework@1

jobs:

workflows:
  version: 2
  yeet-le-jobs:
    jobs:
      - cst/enforce-gem-version-bump
      - cst/rspec-rails-ruby:
          database-migration: true
          database-migration-command: "RAILS_ENV=test bin/rails app:db:prepare"
          rspec-system-args: "CI=true"
          code-climate-report: false
          matrix:
            parameters:
              ruby-version: ["3.4.8", "4.0.0", "4.0.1"]
              rails-version: ["~> 8"]
            alias: required-matrix-tests
          name: test-ruby<< matrix.ruby-version >>-rails<< matrix.rails-version >>
      - cst/publish-gem:
          publish-git: true
          publish-default-gem: true
          requires:
            - required-matrix-tests
            - cst/enforce-gem-version-bump
          filters:
            branches:
              only:
                - main
